- name: Start container with an application
  docker_container:
    name: app
    image: https://hub.docker.com/alextuning/app/app_image:0.1
    command: ["python3", "/opt/app/app.py"]

- name: Add container to networks
  docker_container:
    name: app
    networks:
      - name: TestNet
        ipv4_address: 10.1.1.1
        links:
          - app

- name: Update network with aliases
  docker_container:
    name: app
    networks:
      - name: TestNet
        aliases:
          - app
